/* PJ EXPERIENCE ENGINE */
(()=>{const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();ready(()=>{
const themes={red:'RED CORE',cyan:'CYAN PROTOCOL',violet:'VIOLET VOID',mono:'MONO STEALTH'};let saved='red';try{saved=localStorage.getItem('pjTheme')||'red'}catch(_){};if(!themes[saved])saved='red';
const applyTheme=t=>{document.documentElement.dataset.pjTheme=t;document.querySelectorAll('.pjx-theme-btn').forEach(b=>b.classList.toggle('active',b.dataset.theme===t));try{localStorage.setItem('pjTheme',t)}catch(_){};window.dispatchEvent(new CustomEvent('pjthemechange',{detail:{theme:t}}))};
const dock=document.createElement('div');dock.className='pjx-theme-dock';dock.setAttribute('aria-label','Theme engine');dock.innerHTML=Object.entries(themes).map(([k,v])=>`<button class="pjx-theme-btn" type="button" data-theme="${k}" title="${v}" aria-label="${v}" style="--swatch:${k==='red'?'#ff1e2d':k==='cyan'?'#63f5ff':k==='violet'?'#a77cff':'#e8edf2'}"><i></i></button>`).join('');document.body.appendChild(dock);dock.addEventListener('click',e=>{const b=e.target.closest('[data-theme]');if(b)applyTheme(b.dataset.theme)});applyTheme(saved);
const toast=document.createElement('div');toast.className='pjx-toast';document.body.appendChild(toast);let toastTimer;const notify=t=>{toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1700)};
const share=async(title,url)=>{try{if(navigator.share){await navigator.share({title,text:`Check out ${title} by Pete Junior`,url});return}await navigator.clipboard.writeText(url);notify('LINK COPIED // READY TO TRANSMIT')}catch(e){if(e?.name!=='AbortError')notify('SHARE CANCELLED')}};
document.querySelectorAll('.project-card:not(.coming-soon)').forEach(card=>{const title=card.querySelector('h3')?.textContent?.trim()||'Project';const live=card.querySelector('.project-button.primary')?.href||location.href;const actions=card.querySelector('.project-actions');if(!actions)return;const wrap=document.createElement('div');wrap.className='pjx-actions';const b=document.createElement('button');b.type='button';b.className='pjx-share';b.textContent='SHARE PROJECT ↗';b.addEventListener('click',()=>share(title,live));wrap.appendChild(b);actions.insertAdjacentElement('afterend',wrap)});
const modal=document.createElement('div');modal.className='pjx-modal';modal.innerHTML=`<div class="pjx-modal-card" role="dialog" aria-modal="true" aria-label="Support my work"><div class="pjx-modal-top"><span>SUPPORT // PJ CORE</span><button class="pjx-close" type="button" aria-label="Close">×</button></div><h3>SUPPORT MY WORK.</h3><p>If something I build helps or inspires you, you can support future experiments and projects here.</p><div class="pjx-support-note">PAYMENT DETAILS // COMING NEXT<br>No payment information has been published yet.</div></div>`;document.body.appendChild(modal);const close=()=>modal.classList.remove('open');modal.querySelector('.pjx-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
const contact=document.querySelector('#contact .contact-links');if(contact){const b=document.createElement('button');b.type='button';b.className='pjx-support-btn';b.innerHTML='💚 SUPPORT MY WORK <span>↗</span>';b.onclick=()=>modal.classList.add('open');contact.appendChild(b)};
const projects=document.getElementById('projects');if(projects){const cinema=document.createElement('section');cinema.className='pjx-cinema';cinema.setAttribute('aria-label','Cinematic system motion');cinema.innerHTML='<canvas aria-hidden="true"></canvas><div class="pjx-cinema-copy"><small>MOTION // DIGITAL SIGNAL</small><strong>IDEAS IN MOTION.</strong><p>A living visual layer generated in real time — tuned to the active PJ theme.</p></div>';projects.insertAdjacentElement('afterend',cinema);const c=cinema.querySelector('canvas'),ctx=c.getContext('2d');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(ctx&&!reduced){let w=0,h=0,dpr=1,raf=0,t=0;const particles=Array.from({length:34},()=>({x:Math.random(),y:Math.random(),s:.15+Math.random()*.55,o:.15+Math.random()*.55}));const rgb=()=>getComputedStyle(document.documentElement).getPropertyValue('--pj-accent-rgb').trim()||'255,30,45';const resize=()=>{dpr=Math.min(devicePixelRatio||1,1.6);w=cinema.clientWidth;h=cinema.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};const draw=()=>{t+=.006;ctx.clearRect(0,0,w,h);const col=rgb();const g=ctx.createRadialGradient(w*(.58+Math.sin(t)*.08),h*.45,0,w*.58,h*.45,Math.max(w,h)*.55);g.addColorStop(0,`rgba(${col},.20)`);g.addColorStop(.45,`rgba(${col},.045)`);g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle=`rgba(${col},.11)`;ctx.lineWidth=.7;for(let y=0;y<h;y+=28){ctx.beginPath();for(let x=0;x<=w;x+=18){const yy=y+Math.sin(x*.018+t*9+y*.025)*7+(x/w)*12;x?ctx.lineTo(x,yy):ctx.moveTo(x,yy)}ctx.stroke()}particles.forEach((p,i)=>{p.x+=p.s*.00045;if(p.x>1.05)p.x=-.05;const px=p.x*w,py=(p.y+Math.sin(t*5+i)*.018)*h;ctx.fillStyle=`rgba(${col},${p.o})`;ctx.fillRect(px,py,1.4,1.4);if(i%4===0){ctx.strokeStyle=`rgba(${col},${p.o*.16})`;ctx.beginPath();ctx.moveTo(px-35,py);ctx.lineTo(px,py);ctx.stroke()}});raf=requestAnimationFrame(draw)};resize();draw();addEventListener('resize',resize,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(raf);else{cancelAnimationFrame(raf);draw()}})}}
});})();
